/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author fatema mohamed
 */
public class PersonGUI extends javax.swing.JFrame {

    /**
     * Creates new form PersonGUI
     */
    Database  mainDB;
    public PersonGUI() throws SQLException, ClassNotFoundException {
        mainDB = new Database();
        mainDB.connectDb();
        initComponents();
        
        
        
        ////////////////////////////
        try {
            person p = mainDB.getFirst();
            idTF.setText(""+p.id);
            FirstNameTF.setText(p.FirstName);
            LastNameTF.setText(p.LastName);
            EmailTF.setText(p.email);
            phoneTF.setText(p.phone);

//            updatebtn.setEnabled(true);
//            deletebtn.setEnabled(true);
//            firstbtn.setEnabled(true);
//            prvbtn.setEnabled(true);
//            nextbtn.setEnabled(true);
//            lastbtn.setEnabled(true);
        } catch (SQLException ex) {
            
            idTF.setText("");
            FirstNameTF.setText("");
            LastNameTF.setText("");
            EmailTF.setText("");
            phoneTF.setText("");
            updatebtn.setEnabled(false);
            deletebtn.setEnabled(false);
            firstbtn.setEnabled(false);
            prvbtn.setEnabled(false);
            nextbtn.setEnabled(false);
            lastbtn.setEnabled(false);
            
        }
        //////////////////////////////////////
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        FirstNameTF = new javax.swing.JTextField();
        LastNameTF = new javax.swing.JTextField();
        EmailTF = new javax.swing.JTextField();
        phoneTF = new javax.swing.JTextField();
        newbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        firstbtn = new javax.swing.JButton();
        prvbtn = new javax.swing.JButton();
        nextbtn = new javax.swing.JButton();
        lastbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Email");

        jLabel5.setText("Phone");

        idTF.setEditable(false);

        FirstNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTFActionPerformed(evt);
            }
        });

        newbtn.setText("New");
        newbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbtnActionPerformed(evt);
            }
        });

        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        firstbtn.setText("First");
        firstbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstbtnActionPerformed(evt);
            }
        });

        prvbtn.setText("Privous");
        prvbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prvbtnActionPerformed(evt);
            }
        });

        nextbtn.setText("Next");
        nextbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbtnActionPerformed(evt);
            }
        });

        lastbtn.setText("Last");
        lastbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailTF)
                            .addComponent(phoneTF)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LastNameTF))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstNameTF)
                            .addComponent(idTF)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(newbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updatebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstbtn)
                        .addGap(7, 7, 7)
                        .addComponent(prvbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextbtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FirstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(EmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newbtn)
                    .addComponent(updatebtn)
                    .addComponent(deletebtn)
                    .addComponent(firstbtn)
                    .addComponent(prvbtn)
                    .addComponent(nextbtn)
                    .addComponent(lastbtn))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbtnActionPerformed
 
        try {
            updatebtn.setEnabled(true);             deletebtn.setEnabled(true);
            firstbtn.setEnabled(true);
            prvbtn.setEnabled(true);
            nextbtn.setEnabled(true);
            lastbtn.setEnabled(true);
            person p=new person();
            p.FirstName=FirstNameTF.getText();
            p.LastName=LastNameTF.getText();
            p.email=EmailTF.getText();
            p.phone=phoneTF.getText();
            mainDB.addPerson(p);
            idTF.setText(""+p.id);

        }catch (SQLException ex) {
            Logger.getLogger(PersonGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
        
      



        // TODO add your handling code here:
        // TODO add your handling code here:
        
      



        // TODO add your handling code here:
    }//GEN-LAST:event_newbtnActionPerformed

    private void FirstNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameTFActionPerformed

    private void firstbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstbtnActionPerformed

        try {
            person p = mainDB.getFirst();
            idTF.setText(""+p.id);
            FirstNameTF.setText(p.FirstName);
            LastNameTF.setText(p.LastName);
            EmailTF.setText(p.email);
            phoneTF.setText(p.phone);

        } catch (SQLException ex) {
            Logger.getLogger(PersonGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_firstbtnActionPerformed

    private void lastbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastbtnActionPerformed

        try {
            person p = mainDB.getLast();
            idTF.setText(""+p.id);
            FirstNameTF.setText(p.FirstName);
            LastNameTF.setText(p.LastName);
            EmailTF.setText(p.email);
            phoneTF.setText(p.phone);

        } catch (SQLException ex) {
            Logger.getLogger(PersonGUI.class.getName()).log(Level.SEVERE, null, ex);
        }


        // TODO add your handling code here:


        // TODO add your handling code here:
    }//GEN-LAST:event_lastbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed

        
//            updatePerson(int updatedId,String fn,String ln,String email,String phone) throws SQLException{
        int id = Integer.parseInt(idTF.getText());
        person p=new person();
        person pupdated;
        try {
           
            p.id=id;
            p.FirstName=FirstNameTF.getText();
            p.LastName=LastNameTF.getText();
            p.email=EmailTF.getText();
            p.phone=phoneTF.getText();
            pupdated=mainDB.updatePerson(p);
        } catch (SQLException ex) {
            Logger.getLogger(PersonGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        
        
        
        
        
        
        
        
        

    }//GEN-LAST:event_updatebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        try {
            mainDB.deletePerson(Integer.parseInt(idTF.getText()));
             idTF.setText("");
            FirstNameTF.setText("");
            LastNameTF.setText("");
            EmailTF.setText("");
            phoneTF.setText("");
            nextbtn.setEnabled(false);
            prvbtn.setEnabled(false);
            updatebtn.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(PersonGUI.class.getName()).log(Level.SEVERE, null, ex);
        }



    }//GEN-LAST:event_deletebtnActionPerformed

    private void nextbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbtnActionPerformed
        try {
           int currentId =Integer.parseInt(idTF.getText());
            Vector v = mainDB.getAll();
            int s=0;
            person p;
            for(int i =0;i<v.size();i++){
                p=(person)v.get(i);
                if (currentId == p.id)
                    {
                        System.out.println(i+"  "+ v.size());
                        if(i+1 == v.size())
                        {
                            System.out.println("aaaa");
                              s=0;
                        }
                        else
                        {
                            s=i+1;
                        }
                    }
                }
            
             p=(person)v.get(s);
                    idTF.setText(""+p.id);
                    FirstNameTF.setText(p.FirstName);
                    LastNameTF.setText(p.LastName);
                    EmailTF.setText(p.email);
                    phoneTF.setText(p.phone);
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(PersonGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nextbtnActionPerformed

    private void prvbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prvbtnActionPerformed
        // TODO add your handling code here:
        
        
        
        try {
           int currentId =Integer.parseInt(idTF.getText());
            Vector v = mainDB.getAll();
            int s=0;
            person p;
            for(int i =v.size()-1 ; i>0 ; i--){
                p=(person)v.get(i);
                if (currentId == p.id)
                    {
                        if(i <=0)
                        {
                              s= v.size();
                        }
                        else
                        {
                            s=i-1;
                        }
                    }
                }
            
             p=(person)v.get(s);
                    idTF.setText(""+p.id);
                    FirstNameTF.setText(p.FirstName);
                    LastNameTF.setText(p.LastName);
                    EmailTF.setText(p.email);
                    phoneTF.setText(p.phone);
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(PersonGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_prvbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PersonGUI().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PersonGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(PersonGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailTF;
    private javax.swing.JTextField FirstNameTF;
    private javax.swing.JTextField LastNameTF;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton firstbtn;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton lastbtn;
    private javax.swing.JButton newbtn;
    private javax.swing.JButton nextbtn;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JButton prvbtn;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
